[package]
name = "mpd_client"
version = "1.2.0"
edition = "2021"
description = "Asynchronous user-friendly MPD client"
repository = "https://github.com/elomatreb/mpd_client"
keywords = ["mpd", "async", "client"]
categories = ["network-programming"]
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
chrono = { version = "0.4.26", default-features = false, features = [
    "std",
], optional = true }
mpd_protocol = { version = "1.0.1", features = [
    "async",
], path = "../mpd_protocol" }
serde = { version = "1.0.60", features = ["derive"], optional = true }
specta = { version = "1.0.5", features = ["typescript"], optional = true }
tokio = { version = "1.29.1", features = [
    "rt",
    "net",
    "time",
    "sync",
    "macros",
] }
tracing = "0.1.37"

[dev-dependencies]
assert_matches = "1.5.0"
tokio-test = "0.4.2"
tracing-subscriber = "0.3.17"

[features]
serde = ["dep:serde", "bytes/serde", "chrono?/serde"]
chrono = ["dep:chrono", "specta?/chrono"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
